SELECT 
	   [ProductKey]
      ,[ProductAlternateKey] AS ProductTitleCode
      --,[ProductSubcategoryKey]
      --,[WeightUnitMeasureCode]
      --,[SizeUnitMeasureCode] 
      ,[EnglishProductName] AS [Product Name]
	  ,pc.EnglishProductCategoryName AS [Product Category]
	  ,sc.EnglishProductSubcategoryName AS [Product Subcategory]
      --,[SpanishProductName]
      --,[FrenchProductName]
      --,[StandardCost]
      --,[FinishedGoodsFlag]
      ,[Color] AS [Product Color]
      --,[SafetyStockLevel]
      --,[ReorderPoint]
      --,[ListPrice]
      ,[Size] AS [Product Size]
      --,[SizeRange]
      --,[Weight]
      --,[DaysToManufacture]
      ,[ProductLine] AS [Product Line]
      --,[DealerPrice]
      --,[Class]
      --,[Style]
      ,[ModelName] AS [Product Model Name]
      --,[LargePhoto]
      ,[EnglishDescription] AS [Product Description]
      --,[FrenchDescription]
      --,[ChineseDescription]
      --,[ArabicDescription]
      --,[HebrewDescription]
      --,[ThaiDescription]
      --,[GermanDescription]
      --,[JapaneseDescription]
      --,[TurkishDescription]
      --,[StartDate]
      --,[EndDate]
      ,ISNULL(p.Status,'OutDated') AS [Product Status] 
  FROM [AdventureWorksDW2019].[dbo].[DimProduct] p
  left join[AdventureWorksDW2019].[dbo].[DimProductSubcategory] sc on sc.ProductCategoryKey = p.ProductSubcategoryKey
  left join [AdventureWorksDW2019].[dbo].[DimProductCategory] pc on pc.ProductCategoryKey = sc.ProductCategoryKey
  order by P.ProductKey ASC
